### ISSUE TITLE
Add support for the DNS field in the Interface section

### ISSUE THREAD

**Issue by JMLX42** [mawalu/wireguard-private-networking#29]
Hello,

Thank you for the great work!
I would like to open a PR to add the possibility to customize the `DNS` field of the `Interface` section of the `interface.conf.j2` template with a `wireguard_dns` Ansible var.

Would you accept and merge such PR?

Right now I'm using the following task as a workaround:

```yml
- lineinfile:
    line: "DNS = {{ vpn_ip | ipaddr('address') }}"
    state: present
    insertafter: "PrivateKey = .*"
    path: "{{ client_wireguard_path }}"
  vars:
    ansible_connection: local
  become: no
  run_once: true
  when:
    - client_vpn_ip is defined
    - client_vpn_ip | length > 0
  delegate_to: localhost
```

Regards,
