### ISSUE TITLE
Allow to define the AllowedIPs field globally or for each peer

### ISSUE THREAD

**Issue by promethe42** [mawalu/wireguard-private-networking#33]
Hello,

Here is the setup we need:

- A remote Wireguard VPN mesh hosted in the cloud.
- Some clients (laptops for example) connecting to the VPN and access all the nodes in the mesh.

Here is an example config:

```yaml
vpn:
  hosts:
    vpn-server:
      vpn_ip: 10.1.0.1/32
    minecraft:
      vpn_ip: 10.1.0.253/32
```

and the playbook:

```yaml
- name: Configure VPN network
  hosts: vpn
  remote_user: root
  roles:
    - mawalu.wireguard_private_networking
```

For a laptop to connect to the network, we use the following Interface config:

```
[Interface]
PrivateKey = {private_key}
Address = {address}/24
DNS = 10.1.0.1

[Peer]
PublicKey = {WIREGUARD_SERVER_PUBLIC_KEY}
Endpoint = vpn.hostname.com:5888
PersistentKeepalive = 15
AllowedIPs = 0.0.0.0/0, ::/0
```

But the result is as follow:

- The nodes of the VPN mesh listed above in the `VPN` group can connect to to each other, including to the VPN server.
- But the laptops using the interface above cannot connect to the other nodes in the mesh. Yet they can connect to each other.

As of today, here is what the template contains:

```jinja
{% for node in play_hosts %}
[Peer]
PublicKey = {{ hostvars[node].public.content | b64decode | trim }}
AllowedIPs = {{ hostvars[node].vpn_ip }}
Endpoint = {{ hostvars[node]['public_addr'] | default(hostvars[node]['ansible_host']) | default(hostvars[node]['inventory_hostname']) }}:{{ wireguard_port }}
PersistentKeepalive = 25

{% endfor %}
```

I suspect that `AllowedIPs = {{ hostvars[node].vpn_ip }}` restricts peers to connect to the other listed peers in the conf file. So all the peers must be listed in the conf file. Which is unpractical.

Wouldn't it better to allow for a global/per-host `wireguard_alled_ips` variable? This way it could be set to `0.0.0.0/0, ::/0` and allow any node to connect to any node.

**Comment by promethe42** [comment]
According to this StackOverflow post:

https://stackoverflow.com/a/65453146

> Conversely, like you mentioned, for packets that have come through the tunnel from this remote peer, if they, once unwrapped and decrypted, have a source IP outside of the block(s) specified by AllowedIPs (eg the source IP is 10.1.1.1 instead of 10.129.130.1), the local host will drop them.

So setting `AllowedIPs = {{ hostvars[node].vpn_ip }}` is fine to setup a "remote" Wireguard mesh. But unpractical to generate/manage local peers:

- Remote Wireguard config files would all need to list all those extra peers.
- Local Wireguard config files would all need to list all those extra peers.

**Comment by promethe42** [comment]
> Remote Wireguard config files would all need to list all those extra peers.

I'm trying to use this solution and I'll report back to see how it works.

**Comment by promethe42** [comment]
I actually solved my problem by changing:

```yml
vpn:
  hosts:
    vpn-server:
      vpn_ip: 10.1.0.1/32
    minecraft:
      vpn_ip: 10.1.0.253/32
```

into:

```yml
vpn:
  hosts:
    vpn-server:
      vpn_ip: 10.1.0.1/24
    minecraft:
      vpn_ip: 10.1.0.253/24
```
