### ISSUE TITLE
Missing resolvconf dependency

### ISSUE THREAD

**Issue by JMLX42** [mawalu/wireguard-private-networking#35]
Hi,

On Ubuntu 20.04 (and Debian ?), the `wg-quick` requires `resolvconf` to run. But for some reason, `apt` does not install it as a dependency.

We're using the following workaround:

```yaml
  pre_tasks:
    - name: Install Wireguard dependencies
      apt:
        name: resolvconf
  roles:
    - mawalu.wireguard_private_networking
```

I think we should add this to this role for now and create an upstream issue on the `wg-quick` bug tracker regarding the missing dependency to `resolvconf`.
